In [1]:
import numpy as np

### Задание 1
Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены,  
и найти размерности полученных матриц:
а)  A — матрица  4×2 ,  B — матрица  4×2  
б)  A — матрица  2×5 ,  B — матрица  5×3  
в)  A — матрица  8×3 ,  B — матрица  3×8  
г)  A — матрица  4×4 ,  B — матрица  4×4 .




### Решение 1
а) не определено  
б) определено  
в) определено  
г) определено  

### Задание 2  
Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и 
$B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

### Решение 3
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + 
\begin{pmatrix}4 & -1\\ 0 & 5\end{pmatrix}$ = 
\begin{pmatrix}
1+4 & -2-1\\
3+0 & 0+5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\
3 & 5\\
\end{pmatrix}  
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * 
\begin{pmatrix}4 & -1\\ 0 & 5\end{pmatrix}$ = 
\begin{pmatrix}
1*4-2*0 & -1*1-2*5\\
3*4+0 & -3*1+0*5\\
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\
12 & -3\\
\end{pmatrix}

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A + B =\n{A+B}')
print(f'A * B =\n{A.dot(B)}')

A + B =
[[ 5 -3]
 [ 3  5]]
A * B =
[[  4 -11]
 [ 12  -3]]


### Задание 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод,  
что матрицы одного размера образуют линейное пространство.  
Вычислить линейную комбинацию $3A-2B+4C$ для матриц:  
$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, 
$B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, 
$C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### Решение 3
Матрицы одного размера образуют линейное пространство,  
так как на них определены операции сложения и умножения на скаляр.
3 * \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 
2 * \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 
4 * \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3*1-0+4*2 & 3*7-2*5-4*4\\
3*3-2*2+4 & -6*3+2*1+4*1
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}

### Задание 4
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$. 

### Решение 4
$A^T$ = 
\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}

$A * $$A^T$ = 
\begin{pmatrix}
4*4+1*1 & 4*5-2*1 & 4*2+1*3\\
5*4-2*1 & 5*5+2*2 & 5*2-2*3\\
2*4+3 & 2*5-3*2 & 2*2+3*3
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}  

$A^T$ * A =
\begin{pmatrix}
4*4+5*5+2*2 & 4*1-5*2+2*3\\
1*4-2*5+3*2 & 1*1+2*2+3*3
\end{pmatrix} = 
\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(A.dot(A.T))
print(A.T.dot(A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


### Задание 5
Написать на Python функцию для перемножения двух произвольных матриц,  
не используя NumPy.

In [9]:
def matrix_multi(a: np.array, b: np.array) -> np.array:
    assert a.shape[1] == b.shape[0]
    c = np.zeros([b.shape[1], a.shape[0]])
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[j, i] = sum([_a * _b for _a, _b in zip(a[i, :], b[:, j])])
    return c         

In [10]:
matrix_multi(A, A.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])