In [5]:
import numpy as np

In [6]:
a = np.array([[1,2,0],
              [0,0,5],
              [3,-4,2],
              [1,6,5],
              [0,1,0]])

In [9]:
a.ndim - 2

0

In [13]:
u, s, vh = np.linalg.svd(a, full_matrices=False)

In [11]:
u

array([[ 0.17056501,  0.15680918, -0.53077508],
       [ 0.39287016, -0.52933945,  0.6134793 ],
       [-0.14366152, -0.82449256, -0.52379105],
       [ 0.88843702,  0.06074346, -0.24655277],
       [ 0.08125046,  0.10831843, -0.08231425]])

In [12]:
s

array([8.82486885, 6.14060608, 2.53271528])

In [14]:
vh

array([[ 0.07116451,  0.71702467,  0.69340553],
       [-0.36737824,  0.66514082, -0.65009301],
       [-0.92734505, -0.20847855,  0.31075368]])

In [22]:
euklid_norm = np.max(s)
frab_norm = np.sqrt(np.sum(np.power(s, 2)))
print(f'Евклидова норма = {euklid_norm},\nнорма Фрабениуса = {frab_norm}')

Евклидова норма = 8.824868854820444,
норма Фрабениуса = 11.045361017187263


In [21]:
print(f'Норма Фрабениуса (встроенная функция) = {np.linalg.norm(a, ord="fro")}')
print(f'Евклидова норма (встроенная функция) = {np.linalg.norm(a, ord=2)}')

Норма Фрабениуса (встроенная функция) = 11.045361017187261
Евклидова норма (встроенная функция) = 8.824868854820444
